ToolKits/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^PurchaseRecord/', include('PurchaseRecording.urls')),
    url(r'^admin/', admin.site.urls),
]

PurchaseRecording/models.py
from __future__ import unicode_literals
from datetime import datetime, timedelta
from django.utils import timezone
from django.db import models

# Create your models here.
order_status_type = (
    (0, 'ordered'),
    (1, 'shipped'),
    (2, 'canceled'),
    (3, 'delivered'),
    (4, 'picked')
)
carrier_type = (
    (0, 'Ups'),
    (1, 'Fedex'),
    (2, 'USPS'),
    (3, 'other'),
    (9, 'undefined')
)

pay_method = (
    (0, "Credit Card"),
    (1, "Gift Card"),
    (8, "other"),
    (9, "undefined")
)


class User(models.Model):
    user_name = models.CharField(primary_key=True, max_length=10)
    password = models.CharField(max_length=30)

    def __unicode__(self):
        return self.user_name


class CreditCard(models.Model):
    card_num = models.CharField(unique=True, primary_key=True, max_length=16)
    sec_code = models.CharField(max_length=4, default="0000")
    card_name = models.CharField(unique=True, max_length=20)
    card_exp_date = models.DateField(default=timezone.now().date() + timedelta(days=365 * 5))

    def __unicode__(self):
        return self.card_name


class CashBackSite(models.Model):
    site_url = models.CharField(unique=True, max_length=50, error_messages={'unique': "site already existed"})
    site_name = models.CharField(unique=True, primary_key=True, max_length=20)
    balance = models.FloatField(default=0.0)

    def __unicode__(self):
        return self.site_name


class Merchandiser(models.Model):
    name = models.CharField(max_length=20)
    url = models.CharField(max_length=50)
    reward = models.FloatField(default=0.0)

    def __unicode__(self):
        return self.name


class GiftCard(models.Model):
    brand = models.ForeignKey(Merchandiser, on_delete=models.CASCADE)
    value = models.FloatField()
    card_num = models.CharField(max_length=30)
    pin_num = models.CharField(max_length=10)
    is_used = models.BooleanField(default=False)
    remain_value = models.FloatField(default=value)
    expire_date = models.DateField(default=timezone.now().date() + timedelta(days=365), null=True, blank=True)

    def __unicode__(self):
        return self.brand.name + str(self.remain_value)


class Order(models.Model):
    order_name = models.CharField(max_length=20)
    merchandiser = models.ForeignKey(Merchandiser)
    order_date = models.DateField()
    order_status = models.IntegerField(choices=order_status_type, default=0)
    order_price = models.FloatField(default=0.0)
    mail_link = models.CharField(max_length=100, default="")

    def __unicode__(self):
        return self.order_name


class EarningDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    cashback_site_cashback = models.FloatField(default=0.0)
    cashback = models.ForeignKey(CashBackSite, null=True, blank=True)
    credit_card_cashback = models.FloatField(default=0.0)
    other_cashback = models.FloatField(default=0.0)
    note = models.CharField(blank=True, max_length=200, null=True)
    earing_num = models.FloatField(default=0)

    def __unicode__(self):
        return self.order.order_name


class Address(models.Model):
    addr_name = models.CharField(max_length=20)
    addr_zip = models.CharField(max_length=10)
    addr_line1 = models.CharField(max_length=50, blank=True)
    addr_line2 = models.CharField(max_length=50, blank=True)
    addr_city = models.CharField(max_length=20, blank=True)
    addr_state = models.CharField(max_length=10, blank=True)
    is_default = models.BooleanField(default=False)

    def __unicode__(self):
        return self.addr_name


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item_price = models.FloatField(default=0.0)
    item_num = models.IntegerField(default=1, null=True, blank=True)
    carrier = models.IntegerField(choices=carrier_type, default=9)
    tracking_num = models.CharField(max_length=20, default="undefined")
    deliver_address = models.ForeignKey(Address, default=2)
    pay_method = models.IntegerField(choices=pay_method, default=9)
    gift_card = models.ForeignKey(GiftCard, null=True, blank=True)
    credit_card = models.ForeignKey(CreditCard, null=True)
    earning = models.ForeignKey(EarningDetail, null=True, blank=True)

    def __unicode__(self):
        return self.order.order_name


class PaymentInfo(models.Model):
    payment_date = models.DateField(default=timezone.now)
    paid_to = models.ForeignKey(CreditCard, null=True, blank=True)
    amount = models.FloatField()

    def __unicode__(self):
        return str(self.payment_date)

templates/authority.html
{% extends 'base.html' %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>
            <label for="id_username">Username</label>
            <input type="text" id="id_username" name="username">
        </p>
        <p>
            <label for="id_password">Password</label>
            <input type="password" id="id_password" name="password">
        </p>
        <button type="submit">Login</button>
    </form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Index</title>
    {#    <link href="/static/assets/bootstrap-4.0.0-beta-dist/css/bootstrap.css" rel="stylesheet">#}
    {#    <link href="/static/assets/bootstrap-3.3.6-dist/css/bootstrap-theme.css" rel="stylesheet">#}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
    {% block extra_js %}
    {% endblock %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">PR</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Order
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'orders' %}">Order View</a>
                        <a class="dropdown-item" href="{% url 'ordercreate' %}">Order Reocrd</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Management
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'ccmanagement' %}">Credit Card Management</a>
                        <a class="dropdown-item" href="{% url 'gcmanagement' %}">Gift Card Management</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>
<article>
<div class="container">


    {% block content %}
    {% endblock %}
</div>
</article>

<aside>

</aside>


</body>
</html>

templates/credmanagement.html
{% extends 'base.html' %}

templates/gcmanagement.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-sm">
        <thead class="thead-default">
        <tr>
            <th>#</th>
            <th>Brand</th>
            <th>Value</th>
            <th>Remain Value</th>
            <th>Expire Date</th>
            <th>Redeem</th>
        </tr>
        </thead>
        <tbody>


        {% for gc in gift_cards %}
            {% if gc.is_used == False %}
                <tr>
                    <th scope="row">
                        {{ gc.id }}
                    </th>
                    <td>{{ gc.brand }}</td>
                    <td>{{ gc.value }}</td>
                    <td>{{ gc.remain_value }}</td>
                    <td>{{ gc.expire_date }}</td>
                    <td>
                        <form role="form" method="post">
                            <input class="btn btn-sm" type="button" value="redeem">

                        </form>
                    </td>
                </tr>


            {% endif %}
        {% endfor %}

        </tbody>
    </table>
    <p>-----------------------------------------------</p>
    <div id="content" class="container">
        <h3>New Gift Card</h3>
        <form role="form" action="{% url 'gcmanagement' %}" method="post">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    <div class="col-md-6">
                        {{ field.label_tag }} {{ field }}
                    </div>
                {% endfor %}
            </div>
            <br>
            <input class="btn btn-primary" type="submit" value="Submit">

        </form>
    </div>


{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block extra_js %}
    <script src="{% static 'assets/canvasjs-1.9.10/canvasjs-1.9.10-stable/canvasjs.min.js' %}"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload = function () {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                title: {
                    text: "Order Categories"
                },
                data: [{
                    type: "pie",
                    startAngle: 240,
                    yValueFormatString: "##0.00\"%\"",
                    indexLabel: "{label} {y}",
                    dataPoints: [
                        {% for key, val in status.items %}
                            {y: {{ val }}, label: "{{ key }}"},
                        {% endfor %}
                    ]
                }]
            });
            chart.render();

        }
    </script>



    <div class="row">
        <div class="col-lg-4">
            <div id="chartContainer" style="height: 370px; width: 100%;"></div>


        </div>
        <div class="col-lg-4">


        </div>
        <div class="col-lg-4">


        </div>


    </div>
    <div class="row">
        <div class="col-lg-4">


        </div>
        <div class="col-lg-4">


        </div>
        <div class="col-lg-4">


        </div>


    </div>


{% endblock %}

templates/orderdetail.html
{% extends 'base.html' %}
{% block content %}


    <table class="table">
        <tr>
            <td>
                ID
            </td>
            <td>
                {{ order_detail.order }}
            </td>
            <td>
                Name
            </td>
            <td>
                {{ order_detail.order_name }}
            </td>
        </tr>
        <tr>
            <td>
                item number
            </td>
            <td>
                {{ order_detail.item_num }}
            </td>
            <td>
                item price
            </td>
            <td>
                {{ order_detail.item_price }}
            </td>
        </tr>
        <tr>
            <td>
                carrier
            </td>
            <td>
                {{ order_detail.carrier }}
            </td>
            <td>
                tracking number
            </td>
            <td>
                {{ order_detail.tracking_num }}
            </td>
        </tr>
    <tr>
            <td>
                deliver address
            </td>
            <td>
                {{ order_detail.deliver_address }}
            </td>
            <td>
                credit_card
            </td>
            <td>
                {{ order_detail.credit_card }}
            </td>
        </tr>
    <tr>
        <td>
            earing
        </td>
        <td>
            {{ order_detail.earning }}
        </td>
    </tr>


    </table>




{% endblock %}

templates/orderrecord.html
{% extends 'base.html' %}
{% block content %}
    <div id="content" class="container">
        <h3>New Order Record</h3>
        <div id="content-main">
            <form role="form" autocomplete="on" action="{% url 'addRecord' %}"
                  onsubmit="if(!confirm('Are you going to submit the record?')){return false;}" method="post"
                  id="addRecord">

                {% csrf_token %}
                <div class="form-group">
                    <label for="orderName">Order Name</label>
                    <input type="text" class="form-control" id="orderName" name="orderName">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="orderDate">Order Date</label>
                        <input type="date" class="form-control" id="orderDate" name="orderDate">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="orderPrice">Price</label>
                        <input type="number" step="any" class="form-control" id="orderPrice" name="orderPrice">
                    </div>
                </div>
                <div class="form-group">
                    <label for="gmailLink">Mail Link</label>
                    <input type="url" class="form-control" id="gmailLink" name="gmailLink"
                           placeholder="https://mail.google.com/mail/u/0/#inbox/abc">
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="merchandiser">Merchandiser</label>
                        <select class="form-control" id="merchandiser" name="merchandiser">
                            <option selected disabled>---</option>
                            {% for merchandiser in merchandisers %}
                                <option value={{ merchandiser.id }}>{{ merchandiser.name }}</option>
                            {% endfor %}

                        </select>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="originalPrice">Original Price</label>
                        <input type="number" step="any" class="form-control" id="originalPrice" name="originalPrice">
                    </div>
                </div>
                <div>
                    <p>Optional Field</p>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="itemPrice">Item Price</label>
                        <input type="number" step="any" class="form-control" id="itemPrice" name="itemPrice" value=0>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="itemNum">Item Number</label>
                        <input type="number" class="form-control" id="itemNum" name="itemNum" value=1>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="payMethod">Pay Method</label>
                        <select class="form-control" id="payMethod" name="payMethod">
                            <option selected value=9>---</option>
                            <option value=1>Gift Card</option>
                            {% for creditcard in creditcards %}
                                <option value={{ creditcard.card_num }}>{{ creditcard.card_name }}</option>
                            {% endfor %}
                            <option value=8>Other</option>
                        </select>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="deliverAddress">Deliver Address</label>
                        <select class="form-control" id="deliverAddress" name="deliverAddress">
                            <option selected>---</option>
                            {% for address in addresses %}
                                <option value={{ address.id }}>{{ address.addr_name }}</option>
                            {% endfor %}

                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-3">
                        <label for="cashbackSite">Cash Back Site</label>
                        <select class="form-control" id="cashbackSite" name="cashbackSite">
                            <option selected disabled>---</option>
                            {% for cashback in cashbacks %}
                                <option value="{{ cashback.site_name }}">{{ cashback.site_name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group col-md-3">

                        <label for="cashbackRate">Cashback Rate</label>
                        <div class="input-group">
                            <input type="number" step="any" class="form-control" id="cashbackRate" name="cashbackRate"
                                   value=0>
                            <span class="input-group-addon">%</span>
                        </div>

                    </div>
                    <div class="form-group col-md-3">
                        <label for="creditCardBash">CC Cashback</label>
                        <div class="input-group">
                            <input type="number" step="any" class="form-control" id="creditCardBash"
                                   name="creditCardBash" value=1>
                            <span class="input-group-addon">%</span>
                        </div>
                    </div>
                    <div class="form-group col-md-3">

                        <label for="otherCashback">Other Cashback</label>
                        <div class="input-group">
                            <input type="number" step="any" class="form-control" id="otherCashback"
                                   name="otherCashback" value=0>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="note">Note</label>
                    <input type="text" class="form-control" id="note" name="note">
                </div>

                <button type="submit" class="btn btn-primary">create record</button>

            </form>
        </div>
    </div>




{% endblock %}

templates/orders.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-sm">
        <thead class="thead-default">
        <tr>
            <th>#</th>
            <th>Order Date</th>
            <th>Order Name</th>
            <th>Merchandiser</th>
            <th>Price</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in order %}
            <tr>
                <th scope="row">
                    <a target="_blank" href={{ order_item.mail_link }}> {{ order_item.id }}</a>
                </th>

                <td>{{ order_item.order_date }}</td>
                <td>
                    <a href="/PurchaseRecord/orders/{{ order_item.id }}">
                        {{ order_item.order_name }}
                    </a></td>
                <td>{{ order_item.merchandiser }}</td>
                <td>{{ order_item.order_price }}</td>
                <td><select class="input-group" onchange="">
                    <option selected value={{ order_item.order_status }}>
                        {{ order_item.get_order_status_display }}</option>
                    {% for status_type_val, status_type_display in status_types %}
                        {% if status_type_val != order_item.order_status %}
                            <option value="{{ status_type_val }}">{{ status_type_display }}</option>

                        {% endif %}

                    {% endfor %}
                </select></td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

{% endblock %}